.F
======================================================================
FAIL: test_give_1_2_4_is_prime (tests.test_number_utils.PrimeListTest.test_give_1_2_4_is_prime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tl/courses/dsap/dsap-67/dsap-test/coe_number_testing/tests/test_number_utils.py", line 14, in test_give_1_2_4_is_prime
    self.assertTrue(is_prime)
    ~~~~~~~~~~~~~~~^^^^^^^^^^
AssertionError: False is not true

----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (failures=1)
